# Uncomment the next line to define a global platform for your project

flutter_application_path = "../module"
load File.join(flutter_application_path, ".iOS", "Flutter", "podhelper.rb")

platform :ios, '9.0'


target 'iOS' do
  
  install_all_flutter_pods(flutter_application_path)
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS
  pod 'NXKit', :path => "../../../dev/NXKit"
end
